[tool.black]
line-length = 100
target-version = ['py39', 'py310']
preview_string_processing = true

[tool.isort]
profile = 'black'
multi_line_output = 3

[tool.ruff]
line-length = 100
ignore = ['E501']


[tool.pytest.ini_options]
pythonpath = [
    "app",
]
testpaths = "tests"
